name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Build with Maven
      run: mvn --batch-mode install | tee mvn_install.log

    - name: Display Maven Install Log
      if: failure()
      run: cat mvn_install.log

    - name: Run tests
      run: mvn test
      continue-on-error: true

    - name: Display Surefire Reports
      if: failure()
      run: cat target/surefire-reports/*.txt

  integration-test:
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Build with Maven
      run: mvn --batch-mode install | tee mvn_install.log

    - name: Display Maven Install Log
      if: failure()
      run: cat mvn_install.log

    - name: Verify DATABASE_URL
      run: echo $DATABASE_URL
      env:
        DATABASE_URL: jdbc:postgresql://user:password@localhost:5432/testdb

    - name: Run integration tests
      env:
        DATABASE_URL: jdbc:postgresql://user:password@localhost:5432/testdb
      run: mvn test -Dtest=com.example.AppIntegrationTest
      continue-on-error: true

    - name: Display Surefire Reports
      if: failure()
      run: cat target/surefire-reports/*.txt
